/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as Step3RouteImport } from './routes/step-3'
import { Route as Step2RouteImport } from './routes/step-2'
import { Route as IndexRouteImport } from './routes/index'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const Step3Route = Step3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Step2Route = Step2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/step-2': typeof Step2Route
  '/step-3': typeof Step3Route
  '/summary': typeof SummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/step-2': typeof Step2Route
  '/step-3': typeof Step3Route
  '/summary': typeof SummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/step-2': typeof Step2Route
  '/step-3': typeof Step3Route
  '/summary': typeof SummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/step-2' | '/step-3' | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/step-2' | '/step-3' | '/summary'
  id: '__root__' | '/' | '/step-2' | '/step-3' | '/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Step2Route: typeof Step2Route
  Step3Route: typeof Step3Route
  SummaryRoute: typeof SummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-3': {
      id: '/step-3'
      path: '/step-3'
      fullPath: '/step-3'
      preLoaderRoute: typeof Step3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-2': {
      id: '/step-2'
      path: '/step-2'
      fullPath: '/step-2'
      preLoaderRoute: typeof Step2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Step2Route: Step2Route,
  Step3Route: Step3Route,
  SummaryRoute: SummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
